### ISSUE TITLE
Option 5 fails to enter container shell

### ISSUE THREAD

**Issue by naman-gupta99** [TylerMorton/manager_f1tenth#5]
I am getting the following error when trying to enter into the container shell

```
Error response from daemon: No such container: f1tenth_gym-ros-sim-1
```

**Comment by naman-gupta99** [comment]
The container name actually is `f1tenth_gym_ros_sim_1`

**Comment by TylerMorton** [comment]
This is an issue that I and a few others have noticed during our meetings, so I'm glad you brought it up. It seems that for some machines the naming convention changes i.e. sim-1 vs sim_1.

**Comment by TylerMorton** [comment]
It seems to be a problem with different compose versions and how they generate names: https://docs.docker.com/compose/migrate/#:~:text=Service%20container%20names,valid%20characters%20in%20DNS%20hostnames.

**Comment by naman-gupta99** [comment]
As you can see in the following link, you can force everyone to use version 2 by replacing `docker-compose` with `docker compose`.
This shouldn't be a big issue as `docker compose` ships directly along with Docker.

https://docs.docker.com/compose/migrate/#:~:text=Update%20scripts%20to,.
I'll create a PR with the change

**Comment by TylerMorton** [comment]
Awesome thanks for getting on that!
